services:
    moderation_service:
        container_name: "moderation_service"
        build: ./moderation
        ports:
            - "8002:8000"

    auth_service:
        container_name: "auth_service"
        build: ./auth
        command: uvicorn server:app --reload --workers 1 --host 0.0.0.0 --port 8000
        ports:
            - "8001:8000"
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_LIFETIME=${JWT_LIFETIME}
            - FRONTEND_URL=${FRONTEND_URL}
            - RESET_PASSWORD_LINK=${RESET_PASSWORD_LINK}
            - SENDER_GMAIL=${SENDER_GMAIL}
            - SENDER_GMAIL_PASSWORD=${SENDER_GMAIL_PASSWORD}
            - REDIS_URL=${REDIS_URL}
        depends_on:
            - db
            - redis

    db:
        container_name: "db"
        image: postgres:14.1-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"

    redis:
        container_name: "redis"
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
