version: "3.9"

services:
  db:
    container_name: "moderation_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
    ports:
     - "5432:5432"
    networks:
     - custom

  redis:
    container_name: "moderation_redis"
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - custom


networks:
  custom:
    driver: bridge