services:
    moderation:
        container_name: "moderation"
        build: ./moderation
        ports:
            - "8001:8000"

    api_service:
        container_name: "api_service"
        build: ./auth
        volumes:
            -   ./auth:/usr/src/app
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_LIFETIME=${JWT_LIFETIME}
            - FRONTEND_URL=${FRONTEND_URL}
            - RESET_PASSWORD_LINK=${RESET_PASSWORD_LINK}
            - SENDER_GMAIL=${SENDER_GMAIL}
            - SENDER_GMAIL_PASSWORD=${SENDER_GMAIL_PASSWORD}
            - REDIS_URL=${REDIS_URL}
            - YANDEX_API_KEY=${YANDEX_API_KEY}
            - MODERATION_URL=${MODERATION_URL}
        depends_on:
            - db
            - redis
            - moderation

    db:
        container_name: "db"
        image: postgres:14.1-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"

    redis:
        container_name: "redis"
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
