services:
    moderation_service:
        container_name: "moderation_service"
        build: ./moderation
        ports:
            - 8002:8000
        depends_on:
            - db

    auth_service:
        container_name: "auth_service"
        build: ./auth
        command: uvicorn server:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./auth:/usr/src/app
        ports:
            - 8001:8000
        environment:
            DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
        depends_on:
            - db

    db:
        container_name: "db"
        image: postgres:14.1-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"

    redis:
        container_name: "redis"
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
